FROM alpine:latest
LABEL maintainer="lunksana <zoufeng4@gmail.com>"
RUN apk update && \
    apk upgrade && \
    apk add wget && \
    rm /var/cache/apk/* && \
    kcp_new_ver=$(wget -qO- "https://github.com/xtaci/kcptun/tags"| grep "/xtaci/kcptun/releases/tag/"| head -n 1| awk -F "/tag/v" '{print $2}'| sed 's/\">//')

ENV KCP_LISTEN=":29900"
ENV KCP_TARGET="127.0.0.1:29900"
ENV KCP_KEY="it's a sectect"
ENV KCP_CRYPT="salsa20"
ENV KCP_MODE="fast2"
ENV KCP_MTU=1350
ENV KCP_SNDWND=1024
ENV KCP_NOCOMP="true"
ENV KCP_RCVWND=1024
ENV KCP_DATASHARD=10
ENV KCP_PARITYSHARD=3
ENV KCP_DSCP=0  
